03 (#12)
* Update README.md

* update new status check

* Update connection-check.yml

* Update connection-check.yml

* update

* update workflow

diff --git a/.github/workflows/connection-check.yml b/.github/workflows/connection-check.yml
--- a/.github/workflows/connection-check.yml
+++ b/.github/workflows/connection-check.yml
@@ -8,7 +8,6 @@ on:
 jobs:
   connection_check:
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
@@ -17,16 +16,26 @@ jobs:
         uses: actions/setup-node@v2
         with:
           node-version: '14'
-          
-          
-      - name: Initalize the app
-        run: node init
-  
-      - name: Install dependencies
-        run: npm install
+    
+      # Write package.json content to a file
+      - name: Write package.json
+        run: echo '${{ toJson(env.packageJson) }}'' > package.json
+        env:
+            packageJson: |
+                {
+                    "name": "webapp",
+                    "version": "1.0.0",
+                    "description": "",
+                    "main": "app.js",
+                    "scripts": {
+                    "test": "echo \\"Error: no test specified\\" && exit 1"
+                    },
+                    "author": "Dana",
+                    "license": "ISC"
+                }
 
       - name: Install packages
-        run: npm install express sequelize dotenv mysql2  
+        run: npm install express sequelize dotenv mysql2 bcrypt basic-auth
 
       - name: Run the app
         run: node app.js 
