03 (#22)
* Update README.md

* update new status check

* Update connection-check.yml

* Update connection-check.yml

* update

* update workflow

* update

* test1

* update

* update

* Delete test-draft1.yml

* Update connection-check.yml

* Update connection-check.yml

* Update connection-check.yml

* Update connection-check.yml

* Update connection-check.yml

* Update connection-check.yml

diff --git a/.github/workflows/connection-check.yml b/.github/workflows/connection-check.yml
--- a/.github/workflows/connection-check.yml
+++ b/.github/workflows/connection-check.yml
@@ -58,5 +58,13 @@ jobs:
             MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
             MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
 
-      - name: Wait for application to start
-        run: sleep 10 
+      # Check health endpoint
+      - name: Check /healthz endpoint
+        run: |
+          status_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/healthz)
+          if [ $status_code -eq 200 ]; then
+            echo "Health check passed: status code is 200"
+          else
+            echo "Health check failed: status code is not 200"
+            exit 1
+          fi
