Update connection-check.yml

diff --git a/.github/workflows/connection-check.yml b/.github/workflows/connection-check.yml
--- a/.github/workflows/connection-check.yml
+++ b/.github/workflows/connection-check.yml
@@ -23,6 +23,7 @@ jobs:
       - name: Configure MySQL
         env:
           MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
+          
         run: |
             sudo mysql -e "CREATE USER 'myuser'@'localhost' IDENTIFIED BY 'password';" -p"$MYSQL_ROOT_PASSWORD"
             sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'myuser'@'localhost';" -p"$MYSQL_ROOT_PASSWORD"
@@ -56,5 +57,12 @@ jobs:
             MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
             MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
 
-      - name: Check MySQL Connection
-        run: mysql -h ${{ secrets.MYSQL_HOST }} -P ${{ secrets.MYSQL_PORT }} -u ${{ secrets.DB_USER }} -p"${{ secrets.DB_PASSWORD }}" -e 'SELECT version();'
+      - name: Check /healthz endpoint
+        run: |
+              status_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/healthz)
+              if [ "$status_code" -eq 200 ]; then
+                echo "Health check passed: status code is 200"
+              else
+                echo "Health check failed: status code is $status_code"
+                exit 1
+              fi
